### ISSUE TITLE
strange behavior with motor on

### ISSUE THREAD

**Issue by cgrzemba** [keirf/greaseweazle#394]
I connected a TEAC LW with terminators to my GW V4 via a PC cable. It is jumpered to DS1.
I have strange behavior regarding MOTOR-ON
If I do
$ gw seek --motor-on 0 --drive=a
Then the motor usually starts and the sleds moves to track 0, even with seek on track 79.
But sometimes I get 
```
$ gw seek --motor-on 0 --drive=a
**FATAL ERROR:
Track0 signal absent after seek to cylinder 0
```
Then I try to run
```
$ gw rpm --no 5 --drive=a
Command Failed: GetFluxStatus: No Index
```
or
```
$ gw read --format=sa460.624 --drive=a out.img
Reading c=0-79:h=0-1 revs=2
Format sa460.624
** FATAL ERROR:
Track0 signal absent after seek to cylinder 0
```
I see that the motor is not turning on, there's just a quiet stepping noise.

but if I select drive=2 insteat of drive=a, it works on time
```
$ gw read --format=sa460.624 --drive=2 image.img
Reading c=0-79:h=0-1 revs=2
Format sa460.624
T0.0: IBM FM (16/16 sectors) from Raw Flux (82866 flux in 400.39ms)
T0.1: WARNING: Out of range for format 'sa460.624': No format conversion applied
T1.0: IBM MFM (16/16 sectors) from Raw Flux (76562 flux in 400.44ms)
T1.1: IBM MFM (16/16 sectors) from Raw Flux (76534 flux in 400.40ms)
T2.0: IBM MFM (16/16 sectors) from Raw Flux (78947 flux in 400.42ms)
...
```

What could that be? How do I get more stable behavior?

**Comment by Yserra** [comment]
So, apparently, your drive seems to have Shuggart unit #2. In my experience, it can be:

- Because you are actually using a Shuggart drive with ID #2 on a flat cable. There are some plastic jumpers at the rear of your drive to change the ID number. If you want to use this drive as drive a or b, put the plastic jumper on position "1" and use a ribbon cable with a twist.

- If you are sure your are using an IBM PC drive with a not modifiable ID #1, then what you experience may happen because of the cable. For instance, what you experience would happen with a twisted Amiga 2000, Amiga 3000 or Amiga 4000 cable and an IBM drive installed on the edge: the twist is not the same as the twist on a PC cable. But it "half" works because Motor ON signal selects your drive, or SELECT DRIVE A turns on your drive's motor, but not both at the same time. Here, you would have to change the cable. 

- It also can happen because there is not enough power supplied to your drive. Try to change the power source: use a real Power supply (double check if your drive needs 12V also), disconnect all other devices if your use an USB hub, connect your Greaseweazle board into another USB connector on your computer if you use it to supply power to your drive.
