### ISSUE TITLE
Question about "Unknown Mark"

### ISSUE THREAD

**Issue by OldMadMan** [keirf/greaseweazle#400]
Hello,

I have a question, when I used GW to dump an IBM 1.44MB format floppy disk, during the dump process, GW prompted me that there were read errors on some tracks. 

Later, I used the --revs 10 parameter in the hope that this would eliminate the error by increasing the read time per track. 

The result is that GW did report that the floppy disk was 100% dumpes, but during the dump process, GW reported "Unknown mark f7" and "Unknown mark f3" for the tracks that had no errors last time, but the dump process did not result in this. stop.

What's the meaning of Unknown mark, and does it affect the dump process?

Thank you :)

**Comment by keirf** [comment]
It means that a sector header was found but the type code was unrecognised. I guess since you got a reported 100% good dump that this sector got decoded okay on another revolution.

If you can dump that disk to raw (eg. gw read name.scp) and share the scp file, I can take a look at why the disk was so hard to read and caused weird warning messages like this.
